In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/코로나/코로나 최종과정 시작/코로나 데이터 전처리 v4 (지정 db 없으면 삭제).csv')
# df = pd.read_csv('/content/drive/MyDrive/코로나/코로나 최종과정 시작/코로나 데이터 전처리 v5 (지정db 없어도 포함).csv')

In [ ]:
df.head()

,의뢰구분,결과요약,요양종별,지역,지정(DB),지정(서류) \n비율,해제\n비율,잔여\n비율,목표\n비율,확보\n비율,지정기간(일수),공사기간(일수),설치지원금(DB),청구금,설치지원금 \n대비 \n청구금 비율,설립구분,직접재료비_금액,청구금 대비 직접재료비 비율,간접재료비_금액,청구금 대비 간접재료비 비율,재료비 소계_금액,청구금 대비 재료비 소계 비율,직접노무비_금액,청구금 대비 직접노무비 비율,간접노무비_금액,청구금 대비 간접노무비 비율,노무비 소계_금액,청구금 대비 노무비 소계 비율,기계경비_금액,청구금 대비 기계경비 비율,산재보험료_금액,청구금 대비 산재보험료 비율,고용보험료_금액,청구금 대비 고용보험료 비율,건강보험료_금액,청구금 대비 건강보험료 비율,연금보험료_금액,청구금 대비 연금보험료 비율,산업안전보건관리비_금액,청구금 대비 산업안전보건관리비 비율,기타경비_금액,청구금 대비 기타경비 비율,경비 소계_금액,청구금 대비 경비소계 비율,순공사원가_금액,청구금 대비 순공사원가 비율,일반관리비_금액,청구금 대비 일반관리비 비율,이윤_금액,청구금 대비 이윤 비율,총원가_금액,청구금 대비 총원가 비율,부가가치세_금액,청구금 대비 부가가치세 비율,합계_금액,청구금 대비 합계 비율
0,신규의뢰,수용,종합병원,제주도,39,0.512821,0.512821,0.000000,0.512821,0.512821,126,5,127058000,8250000,0.064931,개인,408500.00,0.049515,0.0,0.000000,408500.00,0.049515,5417311.00,0.656644,0.000,0.000000,5417311.00,0.656644,0.0,0.000000,200440.5070,0.024296,54714.8411,0.006632,0.0000,0.000000,0.000,0.000000,0.0,0.000000,454413.258,0.055080,7.095686e+05,0.086008,6.535380e+06,0.792167,3.267690e+05,0.039608,6.453649e+05,0.078226,7500000.0,0.909091,750000.0,0.090909,8250000.0,1.000000
1,신규의뢰,삭감,요양병원-일반,서울시,170,0.529412,0.529412,0.000000,1.000000,1.000000,193,43,792090710,110000000,0.138873,민간,29718300.00,0.270166,20000.0,0.000182,29738300.00,0.270348,59745000.00,0.543136,597450.000,0.005431,60342450.00,0.548568,0.0,0.000000,603424.5000,0.005486,603424.5000,0.005486,597450.0000,0.005431,597450.000,0.005431,894833.0,0.008135,894833.000,0.008135,4.191415e+06,0.038104,9.427216e+07,0.857020,5.656330e+06,0.051421,7.019019e+06,0.063809,106940000.0,0.972182,10694000.0,0.097218,117634000.0,1.069400
2,신규의뢰,삭감,종합병원,부산시,110,0.509091,0.509091,0.000000,0.509091,0.509091,280,37,215369730,44329000,0.205827,공립,26604810.00,0.600167,0.0,0.000000,26604810.00,0.600167,12556622.00,0.283260,239941.000,0.005413,12796563.00,0.288672,0.0,0.000000,230823.0000,0.005207,63008.0000,0.001421,0.0000,0.000000,0.000,0.000000,0.0,0.000000,0.000,0.000000,2.938310e+05,0.006628,3.969520e+07,0.895468,3.673470e+05,0.008287,2.345880e+05,0.005292,40290000.0,0.908886,4029000.0,0.090889,44319000.0,0.999774
3,신규의뢰,수용,상급종합병원,전북,187,0.582888,0.267380,0.315508,0.155080,0.155080,863,48,4458337760,26230000,0.005883,국립,1920290.75,0.073210,0.0,0.000000,1920290.75,0.073210,19837132.11,0.756276,1983713.211,0.075628,21820845.32,0.831904,42624.0,0.001625,807371.2769,0.030780,220390.5377,0.008402,0.0000,0.000000,0.000,0.000000,0.0,0.000000,1109628.566,0.042304,2.180014e+06,0.083111,2.592115e+07,0.988225,1.218294e+06,0.046447,3.591414e+06,0.136920,30730000.0,1.171559,3073000.0,0.117156,33803000.0,1.288715
4,신규의뢰,수용,종합병원,전북,58,0.448276,0.448276,0.000000,0.775862,0.775862,131,9,146220000,19470000,0.133156,민간,4573945.00,0.234923,0.0,0.000000,4573945.00,0.234923,7862275.00,0.403815,0.000,0.000000,7862275.00,0.403815,0.0,0.000000,290904.1750,0.014941,68401.7925,0.003513,269676.0325,0.013851,353802.375,0.018172,0.0,0.000000,1815000.000,0.093220,2.797784e+06,0.143697,1.523400e+07,0.782435,0.000000e+00,0.000000,2.500000e+06,0.128403,17730000.0,0.910632,1773000.0,0.091063,19503000.0,1.001695

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 56 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   의뢰구분                 151 non-null    object
 1   결과요약                 151 non-null    object
 2   요양종별                 151 non-null    object
 3   지역                   151 non-null    object
 4   지정(DB)               151 non-null    int64
 5   지정(서류)
비율           151 non-null    float64
 6   해제
비율                151 non-null    float64
 7   잔여
비율                151 non-null    float64
 8   목표
비율                151 non-null    float64
 9   확보
비율                151 non-null    float64
 10  지정기간(일수)             151 non-null    int64
 11  공사기간(일수)             151 non-null    int64
 12  설치지원금(DB)            151 non-null    int64
 13  청구금                  151 non-null    int64
 14  설치지원금
대비
청구금 비율    151 non-null    float64
 15  설립구분                 151 non-null    object
 16  직접재료비_금액             151 non-null    float64
 17  청구금 대비 직접재료비 비율      151 non-null    float64
 18  간접재료비_금액             136 non-null    float64
 19  청구금 대비 간접재료비 비율      151 non-null    float64
 20  재료비 소계_금액            151 non-null    float64
 21  청구금 대비  재료비 소계 비율    151 non-null    float64
 22  직접노무비_금액             151 non-null    float64
 23  청구금 대비 직접노무비 비율      151 non-null    float64
 24  간접노무비_금액             151 non-null    float64
 25  청구금 대비 간접노무비 비율      151 non-null    float64
 26  노무비 소계_금액            151 non-null    float64
 27  청구금 대비 노무비 소계 비율     151 non-null    float64
 28  기계경비_금액              151 non-null    float64
 29  청구금 대비 기계경비 비율       151 non-null    float64
 30  산재보험료_금액             151 non-null    float64
 31  청구금 대비 산재보험료 비율      151 non-null    float64
 32  고용보험료_금액             151 non-null    float64
 33  청구금 대비 고용보험료 비율      151 non-null    float64
 34   건강보험료_금액            151 non-null    float64
 35  청구금 대비 건강보험료 비율      151 non-null    float64
 36  연금보험료_금액             151 non-null    float64
 37  청구금 대비 연금보험료 비율      151 non-null    float64
 38  산업안전보건관리비_금액         151 non-null    float64
 39  청구금 대비 산업안전보건관리비 비율  151 non-null    float64
 40  기타경비_금액              151 non-null    float64
 41  청구금 대비 기타경비 비율       151 non-null    float64
 42  경비 소계_금액             151 non-null    float64
 43  청구금 대비 경비소계 비율       151 non-null    float64
 44  순공사원가_금액             151 non-null    float64
 45  청구금 대비 순공사원가 비율      151 non-null    float64
 46  일반관리비_금액             151 non-null    float64
 47  청구금 대비 일반관리비 비율      151 non-null    float64
 48  이윤_금액                151 non-null    float64
 49  청구금 대비 이윤 비율         151 non-null    float64
 50  총원가_금액               151 non-null    float64
 51  청구금 대비 총원가 비율        151 non-null    float64
 52  부가가치세_금액             151 non-null    float64
 53  청구금 대비 부가가치세 비율      151 non-null    float64
 54  합계_금액                151 non-null    float64
 55  청구금 대비 합계 비율         151 non-null    float64
dtypes: float64(46), int64(5), object(5)
memory usage: 66.2+ KB

In [ ]:
df_dum = pd.get_dummies(df, columns = ['의뢰구분', '결과요약', '요양종별', '지역', '설립구분'])

# row 생략 없이 출력
pd.set_option('display.max_rows', None)
# col 생략 없이 출력
pd.set_option('display.max_columns', None)

df_dum

,지정(DB),지정(서류) \n비율,해제\n비율,잔여\n비율,목표\n비율,확보\n비율,지정기간(일수),공사기간(일수),설치지원금(DB),청구금,설치지원금 \n대비 \n청구금 비율,직접재료비_금액,청구금 대비 직접재료비 비율,간접재료비_금액,청구금 대비 간접재료비 비율,재료비 소계_금액,청구금 대비 재료비 소계 비율,직접노무비_금액,청구금 대비 직접노무비 비율,간접노무비_금액,청구금 대비 간접노무비 비율,노무비 소계_금액,청구금 대비 노무비 소계 비율,기계경비_금액,청구금 대비 기계경비 비율,산재보험료_금액,청구금 대비 산재보험료 비율,고용보험료_금액,청구금 대비 고용보험료 비율,건강보험료_금액,청구금 대비 건강보험료 비율,연금보험료_금액,청구금 대비 연금보험료 비율,산업안전보건관리비_금액,청구금 대비 산업안전보건관리비 비율,기타경비_금액,청구금 대비 기타경비 비율,경비 소계_금액,청구금 대비 경비소계 비율,순공사원가_금액,청구금 대비 순공사원가 비율,일반관리비_금액,청구금 대비 일반관리비 비율,이윤_금액,청구금 대비 이윤 비율,총원가_금액,청구금 대비 총원가 비율,부가가치세_금액,청구금 대비 부가가치세 비율,합계_금액,청구금 대비 합계 비율,의뢰구분_신규의뢰,의뢰구분_재의뢰,결과요약_보완,결과요약_삭감,결과요약_수용,결과요약_심사,결과요약_제외,요양종별_노인전문병원,요양종별_병원,요양종별_상급종합병원,요양종별_요양병원-일반,요양종별_종합병원,지역_강원도,지역_경기,지역_경기도,지역_경남,지역_경북,지역_광주,지역_광주시,지역_대구시,지역_대전시,지역_부산시,지역_서울,지역_서울시,지역_울산시,지역_인천,지역_인천시,지역_전남,지역_전북,지역_제주도,지역_충남,지역_충북,설립구분_개인,설립구분_공공,설립구분_공공기관,설립구분_공립,설립구분_국공립,설립구분_국립,설립구분_군병원,설립구분_민간,설립구분_법인,설립구분_시립,설립구분_의료법인,설립구분_특수,설립구분_학교법인,설립구분_학교법인\n(사립)
0,39,0.512821,0.512821,0.000000,0.512821,0.512821,126,5,127058000,8250000,0.064931,4.085000e+05,0.049515,0.000,0.000000,4.085000e+05,0.049515,5.417311e+06,0.656644,0.000000e+00,0.000000,5.417311e+06,0.656644,0.000000e+00,0.000000,2.004405e+05,0.024296,5.471484e+04,0.006632,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,4.544133e+05,0.055080,7.095686e+05,0.086008,6.535380e+06,0.792167,3.267690e+05,0.039608,6.453649e+05,0.078226,7.500000e+06,0.909091,7.500000e+05,0.090909,8.250000e+06,1.000000,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,170,0.529412,0.529412,0.000000,1.000000,1.000000,193,43,792090710,110000000,0.138873,2.971830e+07,0.270166,20000.000,0.000182,2.973830e+07,0.270348,5.974500e+07,0.543136,5.974500e+05,0.005431,6.034245e+07,0.548568,0.000000e+00,0.000000,6.034245e+05,0.005486,6.034245e+05,0.005486,5.974500e+05,0.005431,5.974500e+05,0.005431,8.948330e+05,0.008135,8.948330e+05,0.008135,4.191415e+06,0.038104,9.427216e+07,0.857020,5.656330e+06,0.051421,7.019019e+06,0.063809,1.069400e+08,0.972182,1.069400e+07,0.097218,1.176340e+08,1.069400,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,110,0.509091,0.509091,0.000000,0.509091,0.509091,280,37,215369730,44329000,0.205827,2.660481e+07,0.600167,0.000,0.000000,2.660481e+07,0.600167,1.255662e+07,0.283260,2.399410e+05,0.005413,1.279656e+07,0.288672,0.000000e+00,0.000000,2.308230e+05,0.005207,6.300800e+04,0.001421,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,2.938310e+05,0.006628,3.969520e+07,0.895468,3.673470e+05,0.008287,2.345880e+05,0.005292,4.029000e+07,0.908886,4.029000e+06,0.090889,4.431900e+07,0.999774,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,187,0.582888,0.267380,0.315508,0.155080,0.155080,863,48,4458337760,26230000,0.005883,1.920291e+06,0.073210,0.000,0.000000,1.920291e+06,0.073210,1.983713e+07,0.756276,1.983713e+06,0.075628,2.182085e+07,0.831904,4.262400e+04,0.001625,8.073713e+05,0.030780,2.203905e+05,0.008402,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.109629e+06,0.042304,2.180014e+06,0.083111,2.592115e+07,0.988225,1.218294e+06,0.046447,3.591414e+06,0.136920,3.073000e+07,1.171559,3.073000e+06,0.117156,3.380300e+07,1.288715,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,58,0.448276,0.448276,0.000000,0.775862,0.775862,131,9,146220000,19470000,0.133156,4.573945e+06,0.234923,0.000,0.000000,4.573945e+06,0.234923,7.862275e+06,0.403815,0.000000e+00,0.000000,7.862275e+06,0.403815,0.000000e+00,0.000000,2.909042e+05,0.014941,6.840179e+04,0.003513,2.696760e+05,0.013851,3.538024e+05,0.018172,0.000000e+00,0.000000,1.815000e+06,0.093220,2.797784e+06,0.143697,1.523400e+07,0.782435,0.000000e+00,0.000000,2.500000e+06,0.128403,1.773000e+07,0.910632,1.773000e+06,0.091063,1.950300e+07,1.001695,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
5,33,0.121212,0.121212,0.000000,0.303030,0.303030,170,11,32282000,13530000,0.419119,9.500800e+05,0.070220,20000.000,0.001478,9.700800e+05,0.071698,8.473763e+06,0.626294,8.473763e+04,0.006263,8.558501e+06,0.632557,1.082447e+06,0.080004,8.558501e+04,0.006326,8.558501e+04,0.006326,8.473763e+04,0.006263,8.473763e+04,0.006263,9.443843e+04,0.006980,9.443843e+04,0.006980,1.611970e+06,0.119140,1.114055e+07,0.823396,6.684330e+05,0.049404,1.083890e+06,0.080110,1.289000e+07,0.952698,1.289000e+06,0.095270,1.417900e+07,1.047967,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
6,143,0.699301,0.699301,0.000000,0.699301,0.699301,859,177,685000000,12600000,0.018394,3.860000e+06,0.306349,20000.000,0.001587,3.880000e+06,0.307937,4.980000e+06,0.395238,3.984000e+05,0.031619,5.378400e+06,0.426857,0.000000e+00,0.000000,1.990008e+05,0.015794,5.432184e+04,0.004311,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,4.961600e+05,0.039378,7.494826e+05,0.059483,1.000788e+07,0.794276,6.004730e+05,0.047657,8.545012e+05,0.067818,1.146000e+07,0.909524,1.146000e+06,0.090952,1.260600e+07,1.000476,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,223,0.511211,0.511211,0.000000,0.511211,0.511211,167,59,435105000,278285150,0.639582,3.708600e+07,0.133266,0.000,0.000000,3.708600e+07,0.133266,1.535995e+08,0.551950,0.000000e+00,0.000000,1.535995e+08,0.551950,7.817000e+06,0.028090,5.856749e+06,0.021046,2.841591e+06,0.010211,1.024509e+07,0.036815,0.000000e+00,0.000000,2.860282e+06,0.010278,9.724960e+06,0.034946,3.934567e+07,0.141386,2.300312e+08,0.826602,1.173159e+07,0.042157,1.043851e+07,0.037510,2.522000e+08,0.906265,2.522000e+07,0.090626,2.774200e+08,0.996891,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
8,184,1.000000,1.000000,0.000000,1.000000,1.000000,102,14,179327770,33979000,0.189480,6.770000e+06,0.199241,20000.000,0.000589,6.790000e+06,0.199829,1.860000e+07,0.547397,1.860000e+05,0.005474,1.878600e+07,0.552871,2.500000e+05,0.007357,1.878600e+05,0.005529,1.878600e+05,0.005529,1.860000e+05,0.005474,1.860000e+05,0.005474,2.539000e+05,0.007472,2.539000e+05,0.007472,1.505520e+06,0.044307,2.708152e+07,0.797008,1.624891e+06,0.047820,2.191641e+06,0.064500,3.089000e+07,0.909091,3.089000e+06,0.090909,3.397900e+07,1.000000,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
9,100,0.080000,0.080000,0.000000,0.800000,0.800000,525,30,396627000,50000000,0.126063,1.349711e+07,0.269942,NaN,0.000000,1.349711e+07,0.269942,2.730000e+07,0.546000,1.365000e+06,0.027300,2.866500e+07,0.573300,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,9.275664e+05,0.018551,9.275664e+05,0.018551,4.308968e+07,0.861794,1.292690e+06,0.025854,2.161968e+06,0.043239,4.654000e+07,0.930800,4.654000e+06,0.093080,5.119400e+07,1.023880,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
10,37,0.540541,0.540541,0.000000,0.540541,0.540541,114,2,47664540,5900000,0.123782,2.214571e+06,0.375351,20000.000,0.003390,2.234571e+06,0.378741,1.823399e+06,0.309051,2.279249e+05,0.038631,2.051324e+06,0.347682,0.000000e+00,0.000000,7.589898e+04,0.012864,2.071837e+04,0.003512,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,3.165217e+05,0.053648,4.131390e+05,0.070024,4.699034e+06,0.796446,2.819420e+05,0.047787,4.119607e+05,0.069824,5.390000e+06,0.913559,5.390000e+05,0.091356,5.929000e+06,1.004915,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
11,45,0.488889,0.488889,0.000000,0.222222,0.222222,244,11,131100010,15000000,0.114416,4.563260e+05,0.030422,0.000,0.000000,4.563260e+05,0.030422,9.258556e+06,0.617237,0.000000e+00,0.000000,9.258556e+06,0.617237,5.347830e+05,0.035652,3.425656e+05,0.022838,9.351142e+04,0.006234,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,5.634632e+05,0.037564,1.534323e+06,0.102288,1.124921e+07,0.749947,6.749523e+05,0.044997,1.720174e+06,0.114678,1.364000e+07,0.909333,1.364000e+06,0.090933,1.500400e+07,1.000267,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
12,22,1.000000,1.000000,0.000000,1.590909,1.590909,633,24,121679000,72962000,0.599627,1.621808e+07,0.222281,0.000,0.000000,1.621808e+07,0.222281,3.570241e+07,0.489329,4.462801e+06,0.061166,4.016521e+07,0.550495,3.590000e+06,0.049204,1.486113e+06,0.020368,4.056686e+05,0.005560,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,4.444394e+06,0.060914,9.926175e+06,0.136046,6.630947e+07,0.908822,3.978568e+06,0.054529,8.110493e+06,0.111161,7.839000e+07,1.074395,7.839000e+06,0.107439,8.622900e+07,1.181834,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
13,207,0.198068,0.198068,0.000000,0.657005,0.657005,840,80,7746300,24256000,3.131301,6.188970e+06,0.255152,NaN,0.000000,6.188970e+06,0.255152,1.358269e+07,0.559972,0.000000e+00,0.000000,1.358269e+07,0.559972,1.439249e+06,0.059336,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.439249e+06,0.059336,2.121091e+07,0.874460,0.000000e+00,0.000000,0.000000e+00,0.000000,2.121000e+07,0.874423,2.121000e+06,0.087442,2.333100e+07,0.961865,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
14,303,1.000000,1.000000,0.000000,0.996700,0.996700,333,23,441700000,3815000,0.008637,3.313900e+04,0.008687,NaN,0.000000,3.313900e+04,0.008687,1.768649e+06,0.463604,1.414919e+05,0.037088,1.910141e+06,0.500692,4.292505e+05,0.112517,7.124826e+04,0.018676,1.929242e+04,0.005057,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,3.873844e+05,0.101542,9.071756e+05,0.237792,2.850456e+06,0.747171,1.710273e+05,0.044830,4.452631e+05,0.116714,3.460000e+06,0.906946,3.460000e+05,0.090695,3.806000e+06,0.997641,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
15,217,0.755760,0.755760,0.000000,0.921659,0.921659,165,13,1319600750,264000000,0.200061,6.823320e+07,0.258459,42000.000,0.000159,6.827520e+07,0.258618,1.407630e+08,0.533193,2.815260e+05,0.001066,1.410445e+08,0.534260,2.536702e+07,0.096087,7.052226e+05,0.002671,7.052226e+05,0.002671,7.038150e+05,0.002666,7.038150e+05,0.002666,1.045191e+06,0.003959,1.045191e+06,0.003959,3.027548e+07,0.114680,2.395952e+08,0.907558,2.395952e+05,0.000908,1.715596e+05,0.000650,2.400000e+08,0.909091,2.400000e+07,0.090909,2.640000e+08,1.000000,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
16,54,0.148148,0.148148,0.000000,0.333333,0.333333,224,30,61990000,13683000,0.220729,2.043000e+06,0.149309,40000.000,0.002923,2.083000e+06,0.152233,5.753195e+06,0.420463,5.753195e+04,0.004205,5.810727e+06,0.424668,0.000000e+00,0.000000,5.810727e+04,0.004247,5.810727e+04,0.004247,5.753195e+04,0.004205,5.753195e+04,0.004205,7.836195e+04,0.005727,7.836195e+04,0.005727,3.880023e+05,0.028357,8.281729e+06,0.605257,4.969038e+05,0.036315,6.695633e+05,0.048934,9.440000e+06,0.689907,9.440000e+05,0.068991,1.038400e+07,0.758898,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
17,86,0.383721,0.383721,0.000000,0.383721,0.383721,791,65,533493725,50796075,0.095214,2.631883e+07,0.518127,0.000,0.000000,2.631883e+07,0.518127,1.922942e+07,0.378561,0.000000e+00,0.000000,1.922942e+07,0.378561,6.300000e+05,0.012403,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,6.300000e+05,0.012403,4.617825e+07,0.909091,0.000000e+00,0.000000,0.000000e+00,0.000000,4.617000e+07,0.908928,4.617000e+06,0.090893,5.078700e+07,0.999821,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
18,411,1.000000,1.000000,0.000000,1.000000,0.688564,173,49,2571539850,280500000,0.109079,7.460167e+07,0.265960,NaN,0.000000,7.460167e+07,0.265960,9.414914e+07,0.335648,1.176864e+07,0.041956,1.059178e+08,0.377604,7.954986e+06,0.028360,3.918958e+06,0.013971,1.069770e+06,0.003814,3.337587e+06,0.011899,4.236711e+06,0.015104,4.944399e+06,0.017627,1.316256e+07,0.046925,3.862497e+07,0.137700,2.191444e+08,0.781264,1.314867e+07,0.046876,2.365371e+07,0.084327,2.559400e+08,0.912442,2.559400e+07,0.091244,2.815340e+08,1.003686,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
19,214,0.915888,0.915888,0.000000,0.915888,0.915888,149,39,1593169000,451000000,0.283084,8.648393e+07,0.191760,20000.000,0.000044,8.650393e+07,0.191805,2.540395e+08,0.563281,2.540395e+06,0.005633,2.565799e+08,0.568913,0.000000e+00,0.000000,2.565799e+06,0.005689,2.565799e+06,0.005689,2.540395e+06,0.005633,2.540395e+06,0.005633,3.405435e+06,0.007551,3.405435e+06,0.007551,1.702326e+07,0.037746,3.601071e+08,0.798464,2.049010e+07,0.045433,2.940933e+07,0.065209,4.100000e+08,0.909091,4.100000e+07,0.090909,4.510000e+08,1.000000,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
20,107,0.168224,0.168224,0.000000,0.168224,0.168224,786,15,29797000,2940000,0.098668,1.820000e+05,0.061905,50000.000,0.017007,2.320000e+05,0.078912,1.979040e+06,0.673143,1.918439e+05,0.065253,2.170884e+06,0.738396,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,9.200442e+04,0.031294,9.200442e+04,0.031294,2.494888e+06,0.848601,1.033296e+05,0.035146,8.294752e+04,0.028213,2.670000e+06,0.908163,2.670000e+05,0.090816,2.937000e+06,0.998980,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
21,173,0.751445,0.751445,0.000000,0.693642,0.693642,154,43,1197049000,121000000,0.101082,3.544600e+07,0.292942,0.000,0.000000,3.544600e+07,0.292942,6.463200e+07,0.534149,0.000000e+00,0.000000,6.463200e+07,0.534149,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.000780e+08,0.827091,0.000000e+00,0.000000,1.000780e+07,0.082709,1.100800e+08,0.909752,1.100800e+07,0.090975,1.210000e+08,1.000000,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
22,154,0.980519,0.980519,0.000000,0.993506,0.993506,180,98,1112823200,337733000,0.303492,1.420322e+08,0.420546,2565123.764,0.007595,1.445973e+08,0.428141,1.299112e+08,0.384656,1.434112e+06,0.004246,1.313453e+08,0.388903,2.597962e+07,0.076924,1.313453e+06,0.003889,1.313453e+06,0.003889,1.299112e+06,0.003847,1.299112e+06,0.003847,2.745085e+06,0.008128,2.745085e+06,0.008128,3.669492e+07,0.108651,3.126375e+08,0.925694,1.875825e+07,0.055542,1.867984e+07,0.055310,3.500600e+08,1.036499,3.500600e+07,0.103650,3.850660e+08,1.140149,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
23,219,0.694064,0.694064,0.000000,1.000000,1.000000,160,35,233374100,60500000,0.259240,2.757633e+07,0.455807,0.000,0.000000,2.757633e+07,0.455807,2.164105e+07,0.357703,6.492314e+05,0.010731,2.229028e+07,0.368434,7.553880e+05,0.012486,8.247403e+05,0.013632,1.783222e+05,0.002947,7.563546e+05,0.012502,9.738471e+05,0.016097,7.362806e+05,0.012170,9.843475e+04,0.001627,4.323368e+06,0.071461,5.418998e+07,0.895702,9.132752e+05,0.015095,2.829808e+05,0.004677,5.537000e+07,0.915207,5.537000e+06,0.091521,6.090700e+07,1.006727,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
24,33,0.333333,0.333333,0.000000,0.333333,0.333333,122,31,34841500,20009000,0.574286,6.015269e+06,0.300628,0.000,0.000000,6.015269e+06,0.300628,1.069546e+07,0.534532,0.000000e+00,0.000000,1.069546e+07,0.534532,1.484091e+06,0.074171,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.484091e+06,0.074171,1.819482e+07,0.909332,0.000000e+00,0.000000,0.000000e+00,0.000000,1.819000e+07,0.909091,1.819000e+06,0.090909,2.000900e+07,1.000000,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
25,32,0.500000,0.500000,0.000000,0.593750,0.625000,231,18,163190000,54402700,0.333370,1.349454e+07,0.248049,20000.000,0.000368,1.351454e+07,0.248417,2.158082e+07,0.396687,1.031124e+06,0.018954,2.261195e+07,0.415640,8.748500e+06,0.160810,7.761979e+05,0.014268,2.309143e+05,0.004245,7.625014e+04,0.001402,1.855464e+04,0.000341,3.935044e+04,0.000723,2.112544e+04,0.000388,9.910893e+06,0.182176,4.603738e+07,0.846233,1.914522e+06,0.035192,1.529872e+06,0.028121,4.947000e+07,0.909330,4.947000e+06,0.090933,5.441700e+07,1.000263,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
26,120,1.000000,1.000000,0.000000,1.000000,1.000000,114,7,283997490,30558000,0.107600,4.147000e+06,0.135709,20000.000,0.000654,4.167000e+06,0.136364,1.839353e+07,0.601922,1.839353e+05,0.006019,1.857746e+07,0.607941,2.500000e+05,0.008181,1.857746e+05,0.006079,1.857746e+05,0.006079,1.839353e+05,0.006019,1.839353e+05,0.006019,2.256053e+05,0.007383,2.256053e+05,0.007383,1.440630e+06,0.047144,2.418509e+07,0.791449,1.451106e+06,0.047487,2.146920e+06,0.070257,2.778000e+07,0.909091,2.778000e+06,0.090909,3.055800e+07,1.000000,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
27,30,0.566667,0.566667,0.000000,0.566667,0.566667,186,30,115000000,23133000,0.201157,7.282481e+06,0.314809,0.000,0.000000,7.282481e+06,0.314809,1.029149e+07,0.444884,2.058299e+05,0.008898,1.049732e+07,0.453781,0.000000e+00,0.000000,3.936496e+05,0.017017,2.624331e+04,0.001134,3.643189e+05,0.015749,4.631172e+05,0.020020,0.000000e+00,0.000000,0.000000e+00,0.000000,1.247329e+06,0.053920,1.902713e+07,0.822510,7.610854e+05,0.032900,1.250574e+06,0.054060,2.103000e+07,0.909091,2.103000e+06,0.090909,2.313300e+07,1.000000,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
28,372,0.698925,0.698925,0.000000,1.000000,1.000000,182,32,570063500,356620000,0.625579,1.251960e+08,0.351063,20000.000,0.000056,1.252160e+08,0.351119,1.505008e+08,0.422020,1.505008e+06,0.004220,1.520058e+08,0.426240,0.000000e+00,0.000000,1.520058e+06,0.004262,1.520058e+06,0.004262,1.505008e+06,0.004220,1.505008e+06,0.004220,2.757168e+06,0.007731,2.757168e+06,0.007731,1.156447e+07,0.032428,2.887862e+08,0.809787,1.732717e+07,0.048587,1.808974e+07,0.050726,3.242000e+08,0.909091,3.242000e+07,0.090909,3.566200e+08,1.000000,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
29,137,0.510949,0.510949,0.000000,1.000000,1.000000,137,31,302163330,30818651,0.101993,3.450050e+06,0.111947,0.000,0.000000,3.450050e+06,0.111947,1.705058e+07,0.553255,1.820323e+06,0.059066,1.887090e+07,0.612321,3.500000e+05,0.011357,4.690104e+05,0.015218,1.280267e+05,0.004154,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,1.118227e+06,0.036284,2.065265e+06,0.067013,2.438621e+07,0.791281,1.234741e+06,0.040065,2.396004e+06,0.077745,2.801000e+07,0.908865,2.801000e+06,0.090887,3.081100e+07,0.999752,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
30,86,0.290698,0.290698,0.000000,0.290698,0.290698,258,6,428230000,21700000,0.050674,3.802097e+06,0.175212,0.000,0.000000,3.802097e+06,0.175212,9.924507e+06,0.457351,1.045568e+06,0.048183,1.097008e+07,0.505533,1.197846e+06,0.055200,4.058922e+05,0.018705,1.107970e+05,0.005106,0.000000e+00,0.000000,0.000000e+00,0.000000,2.622586e+05,0.012086,6.363103e+05,0.029323,2.613104e+06,0.120420,1.738528e+07,0.801165,1.022330e+06,0.047112,1.322621e+06,0.060950,1.971000e+07,0.908295,1.971000e+06,0.090829,2.168100e+07,0.999124,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [ ]:
df_dum.columns

Index(['지정(DB)', '지정(서류) \n비율 ', '해제\n비율 ', '잔여\n비율', '목표\n비율', '확보\n비율',
       '지정기간(일수)', '공사기간(일수)', '설치지원금(DB)', '청구금', '설치지원금 \n대비 \n청구금 비율',
       '직접재료비_금액', '청구금 대비 직접재료비 비율', '간접재료비_금액', '청구금 대비 간접재료비 비율',
       '재료비 소계_금액', '청구금 대비  재료비 소계 비율', '직접노무비_금액', '청구금 대비 직접노무비 비율',
       '간접노무비_금액', '청구금 대비 간접노무비 비율', '노무비 소계_금액', '청구금 대비 노무비 소계 비율',
       '기계경비_금액', '청구금 대비 기계경비 비율', '산재보험료_금액', '청구금 대비 산재보험료 비율', '고용보험료_금액',
       '청구금 대비 고용보험료 비율', ' 건강보험료_금액', '청구금 대비 건강보험료 비율', '연금보험료_금액',
       '청구금 대비 연금보험료 비율', '산업안전보건관리비_금액', '청구금 대비 산업안전보건관리비 비율', '기타경비_금액',
       '청구금 대비 기타경비 비율', '경비 소계_금액', '청구금 대비 경비소계 비율', '순공사원가_금액',
       '청구금 대비 순공사원가 비율', '일반관리비_금액', '청구금 대비 일반관리비 비율', '이윤_금액',
       '청구금 대비 이윤 비율', '총원가_금액', '청구금 대비 총원가 비율', '부가가치세_금액',
       '청구금 대비 부가가치세 비율', '합계_금액', '청구금 대비 합계 비율', '의뢰구분_신규의뢰', '의뢰구분_재의뢰',
       '결과요약_보완', '결과요약_삭감', '결과요약_수용', '결과요약_심사', '결과요약_제외', '요양종별_노인전문병원',
       '요양종별_병원', '요양종별_상급종합병원', '요양종별_요양병원-일반', '요양종별_종합병원', '지역_강원도',
       '지역_경기', '지역_경기도', '지역_경남', '지역_경북', '지역_광주', '지역_광주시', '지역_대구시',
       '지역_대전시', '지역_부산시', '지역_서울', '지역_서울시', '지역_울산시', '지역_인천', '지역_인천시',
       '지역_전남', '지역_전북', '지역_제주도', '지역_충남', '지역_충북', '설립구분_개인', '설립구분_공공',
       '설립구분_공공기관', '설립구분_공립', '설립구분_국공립', '설립구분_국립', '설립구분_군병원', '설립구분_민간',
       '설립구분_법인', '설립구분_시립', '설립구분_의료법인', '설립구분_특수', '설립구분_학교법인',
       '설립구분_학교법인\n(사립)'],
      dtype='object')

In [ ]:
df_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 97 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   지정(DB)               151 non-null    int64
 1   지정(서류)
비율           151 non-null    float64
 2   해제
비율                151 non-null    float64
 3   잔여
비율                151 non-null    float64
 4   목표
비율                151 non-null    float64
 5   확보
비율                151 non-null    float64
 6   지정기간(일수)             151 non-null    int64
 7   공사기간(일수)             151 non-null    int64
 8   설치지원금(DB)            151 non-null    int64
 9   청구금                  151 non-null    int64
 10  설치지원금
대비
청구금 비율    151 non-null    float64
 11  직접재료비_금액             151 non-null    float64
 12  청구금 대비 직접재료비 비율      151 non-null    float64
 13  간접재료비_금액             136 non-null    float64
 14  청구금 대비 간접재료비 비율      151 non-null    float64
 15  재료비 소계_금액            151 non-null    float64
 16  청구금 대비  재료비 소계 비율    151 non-null    float64
 17  직접노무비_금액             151 non-null    float64
 18  청구금 대비 직접노무비 비율      151 non-null    float64
 19  간접노무비_금액             151 non-null    float64
 20  청구금 대비 간접노무비 비율      151 non-null    float64
 21  노무비 소계_금액            151 non-null    float64
 22  청구금 대비 노무비 소계 비율     151 non-null    float64
 23  기계경비_금액              151 non-null    float64
 24  청구금 대비 기계경비 비율       151 non-null    float64
 25  산재보험료_금액             151 non-null    float64
 26  청구금 대비 산재보험료 비율      151 non-null    float64
 27  고용보험료_금액             151 non-null    float64
 28  청구금 대비 고용보험료 비율      151 non-null    float64
 29   건강보험료_금액            151 non-null    float64
 30  청구금 대비 건강보험료 비율      151 non-null    float64
 31  연금보험료_금액             151 non-null    float64
 32  청구금 대비 연금보험료 비율      151 non-null    float64
 33  산업안전보건관리비_금액         151 non-null    float64
 34  청구금 대비 산업안전보건관리비 비율  151 non-null    float64
 35  기타경비_금액              151 non-null    float64
 36  청구금 대비 기타경비 비율       151 non-null    float64
 37  경비 소계_금액             151 non-null    float64
 38  청구금 대비 경비소계 비율       151 non-null    float64
 39  순공사원가_금액             151 non-null    float64
 40  청구금 대비 순공사원가 비율      151 non-null    float64
 41  일반관리비_금액             151 non-null    float64
 42  청구금 대비 일반관리비 비율      151 non-null    float64
 43  이윤_금액                151 non-null    float64
 44  청구금 대비 이윤 비율         151 non-null    float64
 45  총원가_금액               151 non-null    float64
 46  청구금 대비 총원가 비율        151 non-null    float64
 47  부가가치세_금액             151 non-null    float64
 48  청구금 대비 부가가치세 비율      151 non-null    float64
 49  합계_금액                151 non-null    float64
 50  청구금 대비 합계 비율         151 non-null    float64
 51  의뢰구분_신규의뢰            151 non-null    uint8
 52  의뢰구분_재의뢰             151 non-null    uint8
 53  결과요약_보완              151 non-null    uint8
 54  결과요약_삭감              151 non-null    uint8
 55  결과요약_수용              151 non-null    uint8
 56  결과요약_심사              151 non-null    uint8
 57  결과요약_제외              151 non-null    uint8
 58  요양종별_노인전문병원          151 non-null    uint8
 59  요양종별_병원              151 non-null    uint8
 60  요양종별_상급종합병원          151 non-null    uint8
 61  요양종별_요양병원-일반         151 non-null    uint8
 62  요양종별_종합병원            151 non-null    uint8
 63  지역_강원도               151 non-null    uint8
 64  지역_경기                151 non-null    uint8
 65  지역_경기도               151 non-null    uint8
 66  지역_경남                151 non-null    uint8
 67  지역_경북                151 non-null    uint8
 68  지역_광주                151 non-null    uint8
 69  지역_광주시               151 non-null    uint8
 70  지역_대구시               151 non-null    uint8
 71  지역_대전시               151 non-null    uint8
 72  지역_부산시               151 non-null    uint8
 73  지역_서울                151 non-null    uint8
 74  지역_서울시               151 non-null    uint8
 75  지역_울산시               151 non-null    uint8
 76  지역_인천                151 non-null    uint8
 77  지역_인천시               151 non-null    uint8
 78  지역_전남                151 non-null    uint8
 79  지역_전북                151 non-null    uint8
 80  지역_제주도               151 non-null    uint8
 81  지역_충남                151 non-null    uint8
 82  지역_충북                151 non-null    uint8
 83  설립구분_개인              151 non-null    uint8
 84  설립구분_공공              151 non-null    uint8
 85  설립구분_공공기관            151 non-null    uint8
 86  설립구분_공립              151 non-null    uint8
 87  설립구분_국공립             151 non-null    uint8
 88  설립구분_국립              151 non-null    uint8
 89  설립구분_군병원             151 non-null    uint8
 90  설립구분_민간              151 non-null    uint8
 91  설립구분_법인              151 non-null    uint8
 92  설립구분_시립              151 non-null    uint8
 93  설립구분_의료법인            151 non-null    uint8
 94  설립구분_특수              151 non-null    uint8
 95  설립구분_학교법인            151 non-null    uint8
 96  설립구분_학교법인
(사립)       151 non-null    uint8
dtypes: float64(46), int64(5), uint8(46)
memory usage: 67.1 KB

In [ ]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()
df_dum_scaled = minmax_scaler.fit_transform(df_dum)

type(df_dum_scaled)

numpy.ndarray

In [ ]:
df_dum_columns = df_dum.columns
df_dum_scaled_df = pd.DataFrame(df_dum_scaled, columns= df_dum_columns)   # 정규화시킨 값을 데이터프레임화

df_dum_scaled_df

,지정(DB),지정(서류) \n비율,해제\n비율,잔여\n비율,목표\n비율,확보\n비율,지정기간(일수),공사기간(일수),설치지원금(DB),청구금,설치지원금 \n대비 \n청구금 비율,직접재료비_금액,청구금 대비 직접재료비 비율,간접재료비_금액,청구금 대비 간접재료비 비율,재료비 소계_금액,청구금 대비 재료비 소계 비율,직접노무비_금액,청구금 대비 직접노무비 비율,간접노무비_금액,청구금 대비 간접노무비 비율,노무비 소계_금액,청구금 대비 노무비 소계 비율,기계경비_금액,청구금 대비 기계경비 비율,산재보험료_금액,청구금 대비 산재보험료 비율,고용보험료_금액,청구금 대비 고용보험료 비율,건강보험료_금액,청구금 대비 건강보험료 비율,연금보험료_금액,청구금 대비 연금보험료 비율,산업안전보건관리비_금액,청구금 대비 산업안전보건관리비 비율,기타경비_금액,청구금 대비 기타경비 비율,경비 소계_금액,청구금 대비 경비소계 비율,순공사원가_금액,청구금 대비 순공사원가 비율,일반관리비_금액,청구금 대비 일반관리비 비율,이윤_금액,청구금 대비 이윤 비율,총원가_금액,청구금 대비 총원가 비율,부가가치세_금액,청구금 대비 부가가치세 비율,합계_금액,청구금 대비 합계 비율,의뢰구분_신규의뢰,의뢰구분_재의뢰,결과요약_보완,결과요약_삭감,결과요약_수용,결과요약_심사,결과요약_제외,요양종별_노인전문병원,요양종별_병원,요양종별_상급종합병원,요양종별_요양병원-일반,요양종별_종합병원,지역_강원도,지역_경기,지역_경기도,지역_경남,지역_경북,지역_광주,지역_광주시,지역_대구시,지역_대전시,지역_부산시,지역_서울,지역_서울시,지역_울산시,지역_인천,지역_인천시,지역_전남,지역_전북,지역_제주도,지역_충남,지역_충북,설립구분_개인,설립구분_공공,설립구분_공공기관,설립구분_공립,설립구분_국공립,설립구분_국립,설립구분_군병원,설립구분_민간,설립구분_법인,설립구분_시립,설립구분_의료법인,설립구분_특수,설립구분_학교법인,설립구분_학교법인\n(사립)
0,0.064677,0.512821,0.512821,0.0,0.020976,0.022465,0.078804,0.003777,0.028499,0.005669,0.020736,0.001403,0.082502,0.000000,0.000000,0.001335,0.072185,0.009536,0.671595,0.000000,0.000000,0.008904,0.664488,0.000000,0.000000,0.012530,0.789326,0.007050,0.514836,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012302,0.542437,0.006683,0.320255,0.005995,0.562298,0.006906,0.508320,0.007508,0.571326,0.005860,0.622189,0.005860,0.622189,0.005860,0.622189,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.281924,0.529412,0.529412,0.0,0.040903,0.043807,0.139493,0.039660,0.177665,0.098968,0.044350,0.102082,0.450152,0.003700,0.003987,0.102089,0.444275,0.148162,0.508404,0.013097,0.065389,0.140355,0.505743,0.000000,0.000000,0.037721,0.178220,0.077747,0.425841,0.019861,0.128476,0.130838,0.187794,0.088850,0.376055,0.024226,0.080113,0.039478,0.141881,0.117504,0.661067,0.119539,0.659921,0.081660,0.466033,0.113972,0.713005,0.113972,0.713005,0.113972,0.713005,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.182421,0.509091,0.509091,0.0,0.020823,0.022302,0.218297,0.033994,0.048307,0.038751,0.065732,0.091387,1.000000,0.000000,0.000000,0.091325,1.000000,0.027754,0.134775,0.005260,0.065165,0.026565,0.124002,0.000000,0.000000,0.014429,0.169167,0.008118,0.110338,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002767,0.024681,0.048140,0.719623,0.007763,0.106350,0.002729,0.038650,0.041509,0.621893,0.041509,0.621893,0.041509,0.621893,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.310116,0.582888,0.267380,1.0,0.006343,0.006794,0.746377,0.044381,1.000000,0.022155,0.001879,0.006596,0.121982,0.000000,0.000000,0.006528,0.112109,0.046331,0.814838,0.043485,0.910497,0.048162,0.921915,0.000973,0.007499,0.050471,1.000000,0.028396,0.652247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030041,0.416612,0.020533,0.309468,0.030633,0.860891,0.025747,0.596079,0.041783,1.000000,0.031116,1.000000,0.031116,1.000000,0.031116,1.000000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.096186,0.448276,0.448276,0.0,0.031735,0.033988,0.083333,0.007554,0.032797,0.015957,0.042524,0.015711,0.391429,0.000000,0.000000,0.015644,0.384586,0.015775,0.308099,0.000000,0.000000,0.014756,0.293127,0.000000,0.000000,0.018185,0.485410,0.008813,0.272721,0.008965,0.327633,0.077481,0.628302,0.000000,0.000000,0.049138,0.918043,0.026351,0.535061,0.017051,0.547475,0.000000,0.000000,0.029085,0.937793,0.016982,0.624407,0.016982,0.624407,0.016982,0.624407,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.054726,0.121212,0.121212,0.0,0.012395,0.013275,0.118659,0.009443,0.007241,0.010510,0.133848,0.003264,0.117001,0.003700,0.032412,0.003264,0.109563,0.017335,0.627961,0.001858,0.075401,0.016422,0.629109,0.024704,0.369201,0.005350,0.205506,0.011027,0.491041,0.002817,0.148146,0.018557,0.216547,0.009377,0.322666,0.002557,0.068739,0.015183,0.443623,0.011848,0.609859,0.014126,0.634031,0.012610,0.585087,0.011720,0.684959,0.011720,0.684959,0.011720,0.684959,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.237148,0.699301,0.699301,0.0,0.028603,0.030634,0.742754,0.166195,0.153645,0.009657,0.005874,0.013259,0.510440,0.003700,0.034804,0.013260,0.507609,0.008420,0.295768,0.008733,0.380668,0.008811,0.326972,0.000000,0.000000,0.012440,0.513109,0.006999,0.334674,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013433,0.387796,0.007059,0.221486,0.010408,0.565510,0.012690,0.611608,0.009941,0.495307,0.010165,0.622812,0.010165,0.622812,0.010165,0.622812,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.369818,0.511211,0.511211,0.0,0.020910,0.022394,0.115942,0.054769,0.097594,0.253276,0.204254,0.127390,0.222048,0.000000,0.000000,0.127330,0.213301,0.387648,0.521075,0.000000,0.000000,0.363545,0.510711,0.178403,0.129630,0.366119,0.683741,0.366119,0.792664,0.340577,0.870838,0.000000,0.000000,0.284005,0.475139,0.263286,0.344152,0.370584,0.526456,0.290047,0.614742,0.247931,0.541025,0.121443,0.273956,0.271899,0.618120,0.271899,0.618120,0.271899,0.618120,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.305141,1.000000,1.000000,0.0,0.040903,0.043807,0.057065,0.012276,0.040223,0.029261,0.060512,0.023255,0.331975,0.003700,0.012906,0.023256,0.325455,0.043174,0.514529,0.004077,0.065902,0.040899,0.512064,0.005706,0.033953,0.011744,0.179618,0.024204,0.429182,0.006183,0.129483,0.040733,0.189268,0.025210,0.345425,0.006874,0.073588,0.014180,0.164980,0.032108,0.569670,0.034340,0.613711,0.025498,0.471077,0.031290,0.622189,0.031290,0.622189,0.031290,0.622189,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.165837,0.080000,0.080000,0.0,0.032722,0.035045,0.440217,0.027384,0.088963,0.043951,0.040259,0.046362,0.449778,NaN,0.000000,0.046297,0.443591,0.065374,0.512521,0.029923,0.328670,0.064542,0.542071,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.025112,0.182695,0.008736,0.069076,0.052454,0.668338,0.027319,0.331799,0.025153,0.315800,0.048305,0.653438,0.048305,0.653438,0.048305,0.653438,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.061360,0.540541,0.540541,0.0,0.022110,0.023679,0.067935,0.000944,0.010691,0.003514,0.039530,0.007607,0.625411,0.003700,0.074327,0.007608,0.626910,0.000366,0.171855,0.004996,0.465091,0.000848,0.210677,0.000000,0.000000,0.004745,0.417935,0.002669,0.272597,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008569,0.528328,0.003891,0.260735,0.003661,0.568815,0.005958,0.613279,0.004793,0.509961,0.003566,0.628621,0.003566,0.628621,0.003566,0.628621,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.074627,0.488889,0.488889,0.0,0.009089,0.009735,0.185688,0.009443,0.029406,0.011858,0.036540,0.001567,0.050689,0.000000,0.000000,0.001499,0.040014,0.019338,0.614939,0.000000,0.000000,0.018097,0.606607,0.012205,0.164528,0.021415,0.741955,0.012048,0.483939,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015255,0.369936,0.014451,0.380873,0.011986,0.497997,0.014264,0.577473,0.020013,0.837556,0.012535,0.622538,0.012535,0.622538,0.012535,0.622538,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.036484,1.000000,1.000000,0.0,0.065072,0.069692,0.538043,0.021719,0.027292,0.065006,0.191494,0.055709,0.370366,0.000000,0.000000,0.055644,0.363285,0.086814,0.431044,0.097830,0.736391,0.092065,0.508574,0.081933,0.227066,0.092900,0.661729,0.052268,0.431611,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.120324,0.599885,0.093491,0.506571,0.081965,0.739961,0.084082,0.699810,0.094359,0.811864,0.082932,0.860136,0.082932,0.860136,0.082932,0.860136,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.343284,0.198068,0.198068,0.0,0.026873,0.028781,0.725543,0.074599,0.001737,0.020345,1.000000,0.021259,0.425135,NaN,0.000000,0.021192,0.418671,0.030372,0.532609,0.000000,0.000000,0.028446,0.522495,0.032847,0.273824,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013556,0.220939,0.024647,0.687629,0.000000,0.000000,0.000000,0.000000,0.020766,0.572285,0.020766,0.572285,0.020766,0.572285,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.502488,1.000000,1.000000,0.0,0.040768,0.043662,0.266304,0.020774,0.099073,0.001602,0.002758,0.000114,0.014473,NaN,0.000000,0.000045,0.003391,0.000226,0.394059,0.003102,0.446514,0.000511,0.435423,0.009797,0.519243,0.004454,0.606743,0.002486,0.392563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010488,1.000000,0.008544,0.885425,0.001312,0.493769,0.003614,0.575335,0.005180,0.852423,0.001468,0.619101,0.001468,0.619101,0.001468,0.619101,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.359867,0.755760,0.755760,0.0,0.037698,0.040375,0.114130,0.011331,0.295985,0.240177,0.063891,0.234380,0.430645,0.007771,0.003488,0.234472,0.424511,0.354893,0.494108,0.006171,0.012838,0.333497,0.484727,0.578938,0.443425,0.044085,0.086786,0.090863,0.207367,0.023397,0.063062,0.154132,0.092178,0.103780,0.183018,0.028297,0.038989,0.285155,0.427014,0.302202,0.738036,0.005064,0.011647,0.001996,0.004746,0.258635,0.622189,0.258635,0.622189,0.258635,0.622189,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.089552,0.148148,0.148148,0.0,0.013634,0.014602,0.167572,0.027384,0.013904,0.010650,0.070491,0.007018,0.248780,0.007401,0.064099,0.007087,0.245258,0.010393,0.332034,0.001261,0.050620,0.009846,0.323756,0.000000,0.000000,0.003632,0.137967,0.007487,0.329660,0.001913,0.099458,0.012599,0.145379,0.007781,0.264744,0.002122,0.056400,0.003654,0.105586,0.008215,0.277636,0.010501,0.466059,0.007790,0.357391,0.007969,0.306683,0.007969,0.306683,0.007969,0.306684,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.142620,0.383721,0.383721,0.0,0.015695,0.016810,0.681159,0.060434,0.119662,0.044681,0.030407,0.090405,0.863305,0.000000,0.000000,0.090342,0.861768,0.044780,0.271791,0.000000,0.000000,0.041960,0.256033,0.014378,0.057235,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005934,0.046181,0.056379,0.740371,0.000000,0.000000,0.000000,0.000000,0.047902,0.621955,0.047902,0.621955,0.047902,0.621955,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
18,0.681592,1.000000,1.000000,0.0,0.040903,0.030164,0.121377,0.045326,0.576793,0.255307,0.034835,0.256256,0.443143,NaN,0.000000,0.256205,0.436881,0.235950,0.210094,0.257983,0.505116,0.249429,0.254627,0.181552,0.130876,0.244983,0.453903,0.137832,0.296057,0.110951,0.281457,0.927818,0.522240,0.490942,0.814859,0.356353,0.462126,0.363796,0.512732,0.276210,0.545692,0.277879,0.601588,0.275191,0.615884,0.275965,0.627012,0.275965,0.627012,0.275965,0.627012,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.354892,0.915888,0.915888,0.0,0.037462,0.040122,0.099638,0.035883,0.357346,0.411646,0.090404,0.297071,0.319512,0.003700,0.000972,0.297092,0.311934,0.643937,0.537365,0.055689,0.067815,0.610005,0.535628,0.000000,0.000000,0.160394,0.184829,0.330585,0.441635,0.084450,0.133241,0.556334,0.194759,0.338134,0.349058,0.092196,0.074362,0.160336,0.140547,0.455367,0.571887,0.433030,0.583066,0.342153,0.476257,0.443460,0.622189,0.443460,0.622189,0.443460,0.622189,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.177446,0.168224,0.168224,0.0,0.006881,0.007369,0.676630,0.013220,0.006683,0.000800,0.031510,0.000625,0.103146,0.009251,0.372901,0.000728,0.121716,0.000763,0.695316,0.004205,0.785595,0.001135,0.784568,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002491,0.308187,0.000867,0.116524,0.000860,0.648246,0.002184,0.451053,0.000965,0.206058,0.000609,0.620853,0.000609,0.620853,0.000609,0.620853,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
21,0.286899,0.751445,0.751445,0.0,0.028372,0.030386,0.104167,0.039660,0.268497,0.109054,0.032281,0.121757,0.488101,0.000000,0.000000,0.121696,0.482345,0.160632,0.495482,0.000000,0.000000,0.150621,0.484564,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.124883,0.615486,0.000000,0.000000,0.116432,0.604068,0.117385,0.623140,0.117385,0.623140,0.117299,0.622189,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.255390,0.980519,0.980519,0.0,0.040637,0.043522,0.127717,0.091596,0.249605,0.307786,0.096922,0.487879,0.700714,0.474592,0.166535,0.496656,0.710146,0.327203,0.280555,0.031438,0.051122,0.310284,0.271223,0.592919,0.354988,0.082107,0.126347,0.169229,0.301897,0.043186,0.090988,0.284499,0.132998,0.272566,0.375737,0.074318,0.080045,0.345617,0.404564,0.395035,0.765657,0.396430,0.712802,0.217325,0.403955,0.378293,0.805587,0.378293,0.805587,0.378293,0.805587,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.363184,0.694064,0.694064,0.0,0.040903,0.043807,0.109601,0.032106,0.052346,0.053579,0.082790,0.094724,0.759467,0.000000,0.000000,0.094662,0.756762,0.050934,0.241804,0.014232,0.129194,0.049286,0.241159,0.017240,0.057619,0.051556,0.442881,0.022976,0.228806,0.025143,0.295721,0.213267,0.556556,0.073107,0.562587,0.002665,0.016023,0.040720,0.266086,0.066562,0.719980,0.019301,0.193730,0.003292,0.034161,0.057905,0.630992,0.057905,0.630992,0.057905,0.630992,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.054726,0.333333,0.333333,0.0,0.013634,0.014602,0.075181,0.028329,0.007815,0.016451,0.183402,0.020662,0.500907,0.000000,0.000000,0.020595,0.495295,0.023004,0.496034,0.000000,0.000000,0.021536,0.485128,0.033871,0.342286,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013978,0.276179,0.020814,0.740738,0.000000,0.000000,0.000000,0.000000,0.017482,0.622189,0.017482,0.622189,0.017482,0.622189,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.053068,0.500000,0.500000,0.0,0.024286,0.027379,0.173913,0.016053,0.036603,0.047988,0.106464,0.046354,0.413300,0.003700,0.008061,0.046357,0.407322,0.050780,0.297851,0.022604,0.228186,0.050056,0.310496,0.199662,0.742109,0.048522,0.463529,0.029752,0.329494,0.002535,0.033154,0.004063,0.011792,0.003907,0.033437,0.000572,0.003824,0.093347,0.678340,0.056200,0.644640,0.040461,0.451638,0.017799,0.205384,0.051490,0.622533,0.051490,0.622533,0.051490,0.622533,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.199005,1.000000,1.000000,0.0,0.040903,0.043807,0.067935,0.005666,0.063700,0.026124,0.034363,0.014245,0.226119,0.003700,0.014351,0.014246,0.218520,0.042647,0.592920,0.004032,0.072467,0.040400,0.592952,0.005706,0.037755,0.011613,0.197509,0.023936,0.471932,0.006115,0.142381,0.040281,0.208120,0.022401,0.341292,0.006108,0.072707,0.013569,0.175543,0.028427,0.561204,0.030667,0.609431,0.024978,0.513126,0.027909,0.622189,0.027909,0.622189,0.027909,0.622189,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
27,0.049751,0.566667,0.566667,0.0,0.023178,0.024824,0.133152,0.027384,0.025794,0.019315,0.064241,0.025015,0.524536,0.000000,0.000000,0.024948,0.519189,0.021974,0.367144,0.004512,0.107121,0.021062,0.366519,0.000000,0.000000,0.024608,0.552844,0.003381,0.088065,0.012111,0.372530,0.101420,0.692202,0.000000,0.000000,0.000000,0.000000,0.011748,0.200772,0.021871,0.608510,0.016085,0.422232,0.014549,0.394830,0.020570,0.622189,0.020570,0.622189,0.020570,0.622189,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.616915,0.698925,0.698925,0.0,0.040903,0.043807,0.129529,0.029273,0.127865,0.325105,0.199783,0.430047,0.584942,0.003700,0.001230,0.430077,0.580369,0.379741,0.334273,0.032992,0.050808,0.359730,0.326065,0.000000,0.000000,0.095022,0.138478,0.195849,0.330881,0.050031,0.099826,0.329589,0.145917,0.273766,0.357404,0.074645,0.076139,0.108922,0.120747,0.364721,0.589133,0.366186,0.623551,0.210459,0.370475,0.350178,0.622189,0.350178,0.622189,0.350178,0.622189,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# df_dum_scaled_df.to_csv('/content/drive/MyDrive/코로나/코로나 최종과정 시작/코로나 데이터 전처리 v4 (지정 db 없으면 삭제) 결과.csv', index = False)
# df_dum_scaled_df.to_csv('/content/drive/MyDrive/코로나/코로나 최종과정 시작/코로나 데이터 전처리 v5 (지정db 없어도 포함) 결과.csv', index = False)

In [ ]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_lean = pd.read_csv('/content/drive/MyDrive/코로나/코로나 최종과정 시작/코로나 데이터 전처리 v4 (지정 db 없으면 삭제) 결과_O1_최종 데이터.csv')

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=321)